Weather feature
Addis0943/Weather-App pull request #1
Opened 2021-06-26 14:04 UTC by Addis0943

2021-06-26 15:44 UTC, Addis0943 commented
Hello TSE
The live link is not working on chrome. so please use another browser to open.
Regards

2021-06-27 07:18 UTC, SajjadAhmad14 commented on src/dom.js
> +const displayData = function (result) {
Please use the ES6 arrow function instead of the function keyword.

2021-06-27 07:18 UTC, SajjadAhmad14 commented on src/dom.js
> +const displayError = function () {
Please use the ES6 arrow function instead of the function keyword.

2021-06-27 07:18 UTC, SajjadAhmad14 commented on src/index.js
> +const cityWeather = function (city_name = 'Addis Ababa') {
Please use the ES6 arrow function instead of the function keyword.

2021-06-27 07:18 UTC, SajjadAhmad14 commented on src/index.js
> +window.onload = function () {
Please use the ES6 arrow function instead of the function keyword.

2021-06-27 07:18 UTC, SajjadAhmad14 commented on src/logic.js
> +export default function clearField() {
Please use the ES6 arrow function instead of the function keyword.

2021-06-27 07:20 UTC, SajjadAhmad14 commented on src/dom.js
> +/* eslint-disable func-names */
Do not disable eslint rules.

2021-06-27 07:20 UTC, SajjadAhmad14 commented on src/logic.js
> +/* eslint-disable camelcase */
Do not disable eslint rules.

2021-06-27 07:21 UTC, SajjadAhmad14 commented on src/index.js
> +/* eslint-disable camelcase */
Do not disable eslint rules.

2021-06-27 07:22 UTC, SajjadAhmad14 commented on package.json
> +  },
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

2021-06-27 07:23 UTC, SajjadAhmad14 commented on package.json
> +  }
Please add webpack related packages as `webpack`, `webpack-cli`, and `webpack-dev-server` etc here.

2021-06-27 07:24 UTC, SajjadAhmad14 commented on package.json
> +  },
Please add webpack related package `webpack-dev-server` here.

2021-06-27 07:24 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] You have mastered Git flow.
- [ ] README includes all the instructions to run the project locally.
## To Improve 🙏
- [ ] All webpack related packages should be included in package.json like `webpack`, `webpack-cli`, `webpack-dev-server etc`. Also, those packages should be added as devDependencies. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/devdep_requirement.png).
- [ ] Please do not disable eslint rules so much. You should correct errors instead.
- [ ] App should have a toggle button to convert Celsius to Fahrenheit and vice versa. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png).
- [ ] Please use ES6 arrow functions instead of function keyword. 
- [x] Please see inline comments for reference.
# Optional
- [ ] App may fetch the current geolocation of the user when the it is first accessed and fetches the weather from that location
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-28 07:07 UTC, Addis0943 commented
Hello TSE
Thank you for your feedback. I did all the requested changes. kindly review it.
Regards

2021-06-28 07:16 UTC, mke2111 commented
### Project under review ⚪

2021-06-28 07:30 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The app runs just fine. 💯 
    2. The toggle functionality works as expected. 👍🏽 

**However, there is one section to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] You are missing the `webpack-dev-server` dependency. Add this to your package JSON file.

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-06-28 07:53 UTC, Addis0943 commented
Hello TSE
Thank you for your feedback. I did all the requested changes. kindly review it.
Regards

2021-06-28 08:32 UTC, Georjane approved these changes
## Status: PR Approved ✔️ ✔️
### Hi Team 🙌

Congratulations on successfully completing this project. 🎊 🎊 
Your project looks great and meets all requirements for approval. 

It's a thumbs up for me. 👍 

You can go ahead and merge this PR. 
Good luck on your next project and Happy Coding 💻

2021-06-28 08:35 UTC, merged